jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - id: setup-haskell-cabal
        uses: "actions/setup-haskell@v1.1"
        with:
          cabal-version: '3.2'
          ghc-version: '8.8.3'
      - uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-${{ matrix.ghc }}-cabal"
          path: "${{ steps.setup-haskell-cabal.outputs.cabal-store }}"
      - name: Install dhall
        run: |
          cabal update
          cd "$(mktemp -d /tmp/dhall-XXX)"
          cabal install dhall
      - name: "Install dhall-to-yaml &c."
        run: |
          cabal update
          cd "$(mktemp -d /tmp/dhall-XXX)"
          cabal install dhall-json
      - name: Check Dhall can be converted to YAML
        run: |
          export PATH=$HOME/.cabal/bin:$PATH
          dhall-to-yaml --file dhall-ci.dhall
          dhall-to-yaml --file haskell-ci.dhall
          dhall-to-yaml --file hlint-ci.dhall
name: Dhall CI
on:
  - push
